### ISSUE TITLE
No model with name 'User' registered in app 'diff_models'

### ISSUE THREAD

**Issue by mosheduminer** [long2ice/fastapi-admin#5]
After installing (from the dev branch) and setting up fastapi-admin, I attempted to run `aerich migrate`, which failed with the error:
```
tortoise.exceptions.ConfigurationError: No model with name 'User' registered in app 'diff_models'.
```
But I didn't register any app named `diff_models`, and I don't see it in the code for this repo... so I'm pretty stumped as to how to fix this. If you could please point me in the right direction, that would be amazing.

**Comment by long2ice** [comment]
fastapi-admin provide builtin auth and permissions control, which include builtin model `User`,`Permission` and `Role`, if you don't need it, just set `permission=False` when call `admin_app.init()`, otherwise you need add `fastapi_admin.models` into tortoise config,such as:
```python
TORTOISE_ORM = {
    'connections': {
        'default': os.getenv('DATABASE_URL')
    },
    'apps': {
        'models': {
            'models': ['examples.models', 'fastapi_admin.models'],
            'default_connection': 'default',
        }
    }
}
```

**Comment by mosheduminer** [comment]
My current config *does* contain `fastapi_admin.models`:
```python
TORTOISE_ORM = {
    "connections": {
        "default": {

            },
        },
    },
    "apps": {
        "models": {
            "models": ["app.models", "fastapi_admin.models", "aerich.models"],
            "default_connection": "default",
        },
    },
}
```
Is this incorrect, or maybe I did something else wrong?

**Comment by long2ice** [comment]
I found that, which is a bug and I fixed it.Now you update fastapi-admin from dev branch, then if you want use builtin auth and permissions control, you should inherit `fastapi_admin.models.AbstractUser` and add you own fields,must contains
`is_active` and `is_superuser` as the `REAMDME.md` said:
```python
from fastapi_admin.models import AbstractUser

class User(AbstractUser):
    last_login = fields.DatetimeField(description="Last Login", default=datetime.datetime.now)
    is_active = fields.BooleanField(default=True, description="Is Active")
    is_superuser = fields.BooleanField(default=False, description="Is SuperUser")
    avatar = fields.CharField(max_length=200, default="")
    intro = fields.TextField(default="")
    created_at = fields.DatetimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.pk}#{self.username}"
```
Then `aerich` will work correctly.

**Comment by mosheduminer** [comment]
I installed the latest `fastapi-admin`. Unfortunately, it still doesn't work, but I'm now thinking that this has nothing to do with `fastapi-admin`, and I must have done something that `aerich` doesn't understand. Fortunately, I can get it working with just `aerich init-db`, for now.
